// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProducerServices.Data;

#nullable disable

namespace ProducerServices.Migrations
{
    [DbContext(typeof(OrderRequestDbContext))]
    partial class OrderRequestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProducerServices.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Electronic City, Bangalore",
                            Name = "Pankaj",
                            Pincode = "560100"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Electronic City, Bangalore",
                            Name = "Pankaj",
                            Pincode = "560100"
                        },
                        new
                        {
                            Id = 2,
                            Address = "HSR, Bangalore",
                            Name = "Alok",
                            Pincode = "560089"
                        },
                        new
                        {
                            Id = 3,
                            Address = "HSR, Bangalore",
                            Name = "Harshita",
                            Pincode = "560088"
                        });
                });

            modelBuilder.Entity("ProducerServices.Entities.OrderRequest", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"), 1L, 1);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.ToTable("OrderRequests");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerId = 1,
                            ProductId = 3,
                            Quantity = 34,
                            Status = "Delayed"
                        },
                        new
                        {
                            OrderId = 3,
                            CustomerId = 2,
                            ProductId = 2,
                            Quantity = 34,
                            Status = "Delayed"
                        },
                        new
                        {
                            OrderId = 4,
                            CustomerId = 4,
                            ProductId = 2,
                            Quantity = 24,
                            Status = "Delayed"
                        },
                        new
                        {
                            OrderId = 2,
                            CustomerId = 3,
                            ProductId = 2,
                            Quantity = 24,
                            Status = "Delayed"
                        });
                });

            modelBuilder.Entity("ProducerServices.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Perfumes"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jeans Pants"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Woman Suits"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
